INSERT INTO users (username, profile_photo_url, bio, email) VALUES
('kanavphull', 'https://pbs.twimg.com/profile_images/1386885117428191232/70SyHOxP_400x400.jpg', 'Hedonist yet Spiritual || IT at NITJ 2024', 'as1mobiles@gmail.com'),
('raj gupta', '/klsadf893724:f//432', 'soon to be updated', 'admin@1shopbuy.com'),
('Sahib Singh', 'https://pbs.twimg.com/profile_images/1465003815820693506/gbTJoe66_400x400.jpg', 'Life is a journey, It drives you MAD.|| IT NITJ''24', '12angeldesignworld@gmail.com'),
('Sakshi Warandani', 'https://vader.news/__export/1612817390103/sites/gadgets/img/2021/02/08/ian_somerhalder_vampires.jpg_246448593.jpg', 'NITJ wish me on 23 jan', 'deepak@24sevenindia.com'),
('Omnicron Larson', '/sdfvsdf', 'Heart Stealer', '101cartinfo@gmail.com'),
('dettol sharma', '/sdfvsdf', 'Dettol Stealer', 'the.yellow.gold@gmail.com'),
('sunil', '/yisadf324//', 'hotel manageemnt', 'deepak@24sevenindia.com'),
('sanjay', '/fduiahj43', 'football lover', 'deepak@24sevenindia.com'),
('Axel Sivert Anker', '/adaskjnas', 'Norwegian', 'gazender.686@gmail.com'),
('Steven', '/acdsccsdc', 'living life my way', 'sravi07@yahoo.com'),
('Jack', 'https://picsum.photos/100', '𝐖𝐞𝐥𝐜𝐨𝐦𝐞 𝐓𝐨 𝐌𝐲 𝐏𝐫𝐨𝐟𝐢𝐥𝐞', 'contact@21fools.com'),
('Oliver', 'https://picsum.photos/101', '𝐎𝐟𝐟𝐢𝐜𝐢𝐚𝐥 𝐀𝐜𝐜𝐨𝐮𝐧𝐭', 'the.yellow.gold@gmail.com'),
('James', 'https://picsum.photos/102', '𝐖𝐢𝐬𝐡 𝐌𝐞 𝐎𝐧 𝟑 𝐎𝐜𝐭𝐨𝐛𝐞𝐫', 'contact@21fools.com'),
('Charlie', 'https://picsum.photos/103', 'aap yha aae kisliye', 'sravi07@yahoo.com'),
('Harris', 'https://picsum.photos/104', '𝐒𝐚𝐧𝐬𝐤𝐚𝐫𝐢 𝐋𝐚𝐝𝐤𝐚', 'pawan.modi1@gmail.com'),
('Lewis', 'https://picsum.photos/105', 'aapne bulaya isilye', 'as1mobiles@gmail.com'),
('Leo', 'https://picsum.photos/106', '𝐆𝐲𝐦 𝐋ø𝐯è𝐫', 'pawan.modi1@gmail.com'),
('Noah', 'https://picsum.photos/107', 'aae hai toh kaam bi btiye', 'sunglasses.24@gmail.com'),
('Alfie', 'https://picsum.photos/108', '𝐒𝐢𝐧𝐠𝐥𝐞', 'deepak@24sevenindia.com'),
('Rory', 'https://picsum.photos/109', 'phle zara aap muskurae', 'pawan.modi1@gmail.com'),
('Alexander', 'https://picsum.photos/110', '𝐑𝐞𝐬𝐩𝐞𝐜𝐭 𝐅𝐨𝐫 𝐀𝐥𝐥', 'umesh.agarwal@24x7safebuy.com'),
('Max', 'https://picsum.photos/111', '𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦 𝐊𝐢𝐧𝐠', 'as1mobiles@gmail.com'),
('Logan', 'https://picsum.photos/112', '𝐂𝐚𝐤𝐞 𝐌𝐮𝐫𝐝𝐞𝐫 𝐎𝐧 𝟏𝟕 𝐉𝐮𝐧𝐞', '101cartinfo@gmail.com'),
('Harry', 'https://picsum.photos/113', 'hhddsgb', 'shyamsunder121@gmail.com'),
('Theo', 'https://picsum.photos/114', '♥️𝐏𝐡𝐨𝐭𝐨𝐠𝐫𝐚𝐩𝐡𝐲', 'info@3coinsplus.com'),
('Thomas', 'https://picsum.photos/115', 'siudgfibsiugs', 'wasif1@2dayenterprises.com'),
('Brodie', 'https://picsum.photos/116', '𝐌𝐮𝐬𝐢𝐜 𝐀𝐝𝐝𝐢𝐜𝐭', 'shyamsunder121@gmail.com'),
('Archie', 'https://picsum.photos/117', 'uhiusgfufiusf', 'wasif1@2dayenterprises.com'),
('Jacob', 'https://picsum.photos/118', '𝐒𝐢𝐧𝐠𝐥𝐞', 'mail@3gmobileworld.in'),
('Finlay', 'https://picsum.photos/119', 'usdsgbcu', 'mail@3gmobileworld.in'),
('Finn', 'https://picsum.photos/120', '𝐏𝐫𝐨𝐮𝐝 𝐓𝐨 𝐁𝐞 𝐇𝐢𝐧𝐝𝐮', 'pawan.modi1@gmail.com'),
('Daniel', 'https://picsum.photos/121', 'hucussgcusn', 'shyamsunder121@gmail.com'),
('Joshua', 'https://picsum.photos/122', '𝐁𝐢𝐠 𝐅𝐚𝐧 𝐎𝐟 𝐌𝐚𝐡𝐚𝐤𝐚𝐥', 'sunglasses.24@gmail.com'),
('Oscar', 'https://picsum.photos/123', '𝐌𝐫.𝐩𝐞𝐫𝐟𝐞𝐜𝐭', 'gazender.686@gmail.com'),
('Arthur', 'https://picsum.photos/124', '𝐇𝐚𝐭𝐞 𝐦𝐞 𝐨𝐫 𝐃𝐚𝐭𝐞 𝐦𝐞', '.'),
('Hunter', 'https://picsum.photos/125', '𝐩𝐡𝐨𝐭𝐨𝐡𝐨𝐥𝐢𝐤', 'mail@3gmobileworld.in'),
('Ethan', 'https://picsum.photos/126', 'gygyuuy', 'deepak@24sevenindia.com'),
('Mason', 'https://picsum.photos/127', '𝐟𝐨𝐨𝐝𝐲', 'sunglasses.24@gmail.com'),
('Harrison', 'https://picsum.photos/128', 'gfytfvy', 'contact@21fools.com'),
('Freddie', 'https://picsum.photos/129', '𝐬𝐢𝐧𝐠𝐥𝐞', 'contact@21fools.com'),
('Ollie', 'https://picsum.photos/130', 'fytfysguf', 'mail@3gmobileworld.in'),
('Adam', 'https://picsum.photos/131', '𝐔 𝐰𝐢𝐥𝐥 𝐟𝐢𝐧𝐝 𝐚 𝐛𝐨𝐲 𝐛𝐞𝐭𝐭𝐞𝐫 𝐭𝐡𝐚𝐧 𝐦𝐞 𝐛𝐮𝐭 𝐔 𝐝𝐨𝐧''𝐭 𝐟𝐢𝐧𝐝 𝐛𝐨𝐲 𝐥𝐢𝐤𝐞 𝐦𝐞', 'sravi07@yahoo.com'),
('William', 'https://picsum.photos/132', 'fyasu', 'admin@1shopbuy.com'),
('Jaxon', 'https://picsum.photos/133', '𝙊𝙛𝙛𝙞𝙘𝙞𝙖𝙡 𝙖𝙘𝙘𝐨𝐮𝐧𝐭', 'info@3coinsplus.com'),
('Aaron', 'https://picsum.photos/134', 'ytyftftyi', 'gazender.686@gmail.com'),
('Cameron', 'https://picsum.photos/135', 'uygdghfios', 'shyamsunder121@gmail.com'),
('Liam', 'https://picsum.photos/136', 'ygyugdysgc', 'wasif1@2dayenterprises.com'),
('George', 'https://picsum.photos/137', '𝙈𝙪𝙨𝙞𝙘 𝙡𝙤𝙫𝙚𝙧', 'as1mobiles@gmail.com'),
('Jamie', 'https://picsum.photos/138', 'ygsgsogt', 'pawan.modi1@gmail.com'),
('Callum', 'https://picsum.photos/139', '𝙎𝙥𝙤𝙧𝙩𝙨 𝙡𝙤𝙫𝙚𝙧', 'mail@3gmobileworld.in');
