CREATE DATABASE Lec1_DB;
USE Lec1_DB;
-- 1. PERSON Table
CREATE TABLE PERSON (
    PERSON_ID SMALLINT UNSIGNED,
    FNAME VARCHAR(20),
    LNAME VARCHAR(20),
	EYE_COLOR ENUM('BR', 'BL', 'GR'),
	BIRTH_DATE DATE,
	STREET VARCHAR(30),
	CITY VARCHAR(20),
	STATE VARCHAR(20),
	COUNTRY VARCHAR(20),
	POSTAL_CODE VARCHAR(20),
	CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID)
);
DESC Person;

-- 2. FAVORITE_FOOD Table
CREATE TABLE FAVORITE_FOOD (
    PERSON_ID SMALLINT UNSIGNED,
    FOOD VARCHAR(20),
    CONSTRAINT PK_FAVORITE_FOOD PRIMARY KEY (PERSON_ID, FOOD),
    CONSTRAINT FK_FAV_FOOD_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID)
);
DESC FAVORITE_FOOD; 

SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE PERSON
MODIFY PERSON_ID SMALLINT UNSIGNED AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO PERSON (PERSON_ID, FNAME, LNAME, EYE_COLOR, BIRTH_DATE)
VALUES (NULL, 'Kerolos', 'Hanii', 'BL', '2003-09-25');

SELECT * FROM PERSON ;

INSERT INTO FAVORITE_FOOD (PERSON_ID, FOOD)
VALUES (1, 'pizza');

INSERT INTO FAVORITE_FOOD (PERSON_ID, FOOD)
VALUES (1, 'cookies');

INSERT INTO FAVORITE_FOOD (PERSON_ID, FOOD)
VALUES (1, 'nachos');

SELECT *
FROM FAVORITE_FOOD
ORDER BY FOOD;

INSERT INTO PERSON (PERSON_ID, FNAME, LNAME, EYE_COLOR, BIRTH_DATE, STREET, CITY, STATE, COUNTRY, POSTAL_CODE)
VALUES (NULL, 'Susan', 'Smith', 'BL', '1975-11-02', '23 Maple St.', 'Arlington', 'VA', 'USA', '20220');

INSERT INTO PERSON (PERSON_ID, FNAME, LNAME, EYE_COLOR, BIRTH_DATE, STREET, CITY, STATE, COUNTRY, POSTAL_CODE)
VALUES (NULL, 'mohamed ', 'Samy', 'GR', '1988-10-10', '23 New Cairo.', 'Cairo', NULL,'Egypt', '20220');

SELECT * FROM PERSON;