
SELECT DISTINCT CITY
FROM STATION
WHERE NOT(CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%')
  AND NOT(CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U');

-- Alternative solution using REGEXP (MySQL)
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '^[AEIOU]'
  AND CITY NOT REGEXP '[AEIOU]$';

--Alternative solution using LEFT and RIGHT functions
SELECT DISTINCT CITY
FROM STATION
WHERE LEFT(CITY, 1) NOT IN ('A', 'E', 'I', 'O', 'U')
   AND RIGHT(CITY, 1) NOT IN ('A', 'E', 'I', 'O', 'U');
