-- Query for shortest city name
SELECT CITY, LENGTH(CITY) AS name_length
FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1;

-- Query for longest city name  
SELECT CITY, LENGTH(CITY) AS name_length
FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1;
