name: Update README with SQL count

on:
  workflow_dispatch:
  push:
    paths:
      - '**.sql'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count .sql files
        id: count_sql
        run: |
          count=$(find . -type f -name "*.sql" | wc -l)
          echo "SQL_COUNT=$count" >> $GITHUB_ENV
          echo "Counted $count SQL files"

      - name: Commit and push if changed
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    git config --global user.name 'github-actions'
    git config --global user.email 'github-actions@github.com'
    if ! git diff --quiet; then
      git add README.md
      git commit -m "Update SQL problem count to $SQL_COUNT"
      git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
    else
      echo "No changes to commit"
    fi

